font_size 15.5
background_opacity 0.95
foreground #d0d0d0
background #1e1e1e
cursor #ffffff
enable_audio_bell no
confirm_os_window_close 0
hide_window_decorations yes
window_margin_width 10
allow_remote_control yes
#key bindings
map cmd+n launch --cwd=current --type=os-window

