font_size 15.5
background_opacity 0.95
# foreground #d0d0d0
# background #1e1e1e
# cursor #ffffff
# active_border_color #A4EEF5
enable_audio_bell no
close_window_with_confirmation 1
hide_window_decorations yes
window_padding_width 2
allow_remote_control yes

enabled_layouts tall, stack

#key bindings
map cmd+enter launch --cwd=current --type=os-window
map cmd+n launch --cwd=current 
map cmd+w close_window
map cmd+] next_window
map cmd+[ previous_window
map cmd+l next_layout
map cmd+e layout_action rotate
map cmd+f move_window_to_top

map ctrl+equal increase_font_size
map ctrl+minus decrease_font_size


include current-theme.conf
