bold_font auto
italic_font auto
font_size 16.0
background_opacity 0.95
foreground #d0d0d0
background #1e1e1e
cursor #ffffff
enable_audio_bell no
confirm_os_window_close 0
hide_window_decorations yes
window_margin_width 10
map super+c copy_to_clipboard
map super+v paste_from_clipboard
