#!/bin/bash
set -e

if [ ! -d "$HOME/.oh-my-zsh" ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" ]; then
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
    "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
fi

ZSHRC="$HOME/.zshrc"
if ! grep -q 'ZSH_THEME="powerlevel10k/powerlevel10k"' "$ZSHRC"; then
  sed -i 's/^ZSH_THEME=.*/ZSH_THEME="powerlevel10k\/powerlevel10k"/' "$ZSHRC" ||
    echo 'ZSH_THEME="powerlevel10k/powerlevel10k"' >>"$ZSHRC"
fi

echo "Powerlevel10k installed! Restart your terminal and run 'p10k configure' to finish setup."

# if [ -n "$plugins" ]; then
#   plugin_content=$(echo "$plugins" | sed -e 's/plugins=(//' -e 's/)//')
#
#   for plugin in "${plugins[@]}"; do
#     repo="git@github.com:${plugin}/${plugin}.git"
#
#     target_dir="$HOME/.oh-my-zsh/custom/plugins/$plugin"
#     if [ ! -d "$target_dir" ]; then
#       echo "Installing: $plugin..."
#       git clone --depth 1 "$repo" "$target_dir"
#     fi
#   done
# else
#   echo "No plugins line found"
# fi

if grep -qi 'arch' /etc/os-release; then
  tmpdir=$(mktemp -d)
  cd "$tmpdir"

  git clone https://aur.archlinux.org/yay.git
  cd yay

  makepkg -si --noconfirm

  cd ~
  rm -rf "$tmpdir"

  echo "yay installed successfully! Version:"
  yay --version
else
  echo "This script only installs yay on Arch Linux systems."
fi

echo "Do you want to enable Git credential caching (store credentials in ~/.git-credentials)? [y/N]"
read -r response
if [[ "$response" =~ ^[Yy]$ ]]; then
  git config --global credential.helper store
  echo "Git credential helper enabled. Your credentials will be saved in ~/.git-credentials."
else
  echo "Skipped enabling Git credential helper."
fi
