#!/bin/bash
set -e

if [ ! -d "$HOME/.oh-my-zsh" ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" ]; then
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
    "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
fi

ZSHRC="$HOME/.zshrc"
if ! grep -q 'ZSH_THEME="powerlevel10k/powerlevel10k"' "$ZSHRC"; then
  sed -i 's/^ZSH_THEME=.*/ZSH_THEME="powerlevel10k\/powerlevel10k"/' "$ZSHRC" ||
    echo 'ZSH_THEME="powerlevel10k/powerlevel10k"' >>"$ZSHRC"
fi

echo "Powerlevel10k installed! Restart your terminal and run 'p10k configure' to finish setup."

tmpdir=$(mktemp -d)
cd "$tmpdir"

git clone https://aur.archlinux.org/yay.git
cd yay

makepkg -si

cd ~
rm -rf "$tmpdir"

echo "yay installed successfully! Version:"
yay --version
