#!/bin/bash

install_pkg() {
  local pkg="$1"

  if command -v apt-get >/dev/null 2>&1; then
    echo "Installing $pkg using apt-get..."
    sudo apt-get update
    sudo apt-get install -y "$pkg"
  elif command -v pacman >/dev/null 2>&1; then
    echo "Installing $pkg using pacman..."
    sudo pacman -Sy --noconfirm "$pkg"
  elif command -v brew >/dev/null 2>&1; then
    echo "Installing $pkg using brew..."
    brew install "$pkg"
  else
    echo "No supported package manager (apt-get, pacman, brew) found. Please install $pkg manually."
    exit 1
  fi
}

check_command() {
  local cmd="$1"
  echo "Checking for command: $cmd"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Command '$cmd' not found. Installing..."
    install_pkg "$cmd"
  fi
}

confirm() {
  local prompt="${1:-Are you sure?}"
  local default="${2:-N}"
  local response

  if [[ "$default" == "Y" ]]; then
    prompt="$prompt [Y/n] "
  else
    prompt="$prompt [y/N] "
  fi
  echo -n "$prompt"
  read -r response

  if [[ -z "$response" ]]; then
    response=$default
  fi

  case "$response" in
  [yY]) return 0 ;; # yes
  [nN]) return 1 ;; # no
  *)
    echo "Invalid input. Please answer y or n."
    return 1
    ;;
  esac
}

# end of utility functions
# begin of module functions and global variables

tmpdir=$(mktemp -d)

get_repo() {
  REPOS=(
    "http://10.0.0.152:3000/lfy/dotfiles"
    "http://silvertech:3000/lfy/dotfiles"
    "https://github.com/flin16/dotfiles"
  )
  if yadm rev-parse --git-dir 2>/dev/null; then
    if confirm "Detecting existing yadm repository, remove it?"; then
      repo=$(yadm rev-parse --git-dir)
      echo "Removing existing yadm repository at $repo"
      rm -rf "$repo"
    else
      echo "Exiting without changes."
      exit 1
    fi
  fi

  for repo in "${REPOS[@]}"; do
    echo "🔄 Trying clone $repo ..."

    if yadm clone $repo; then
      echo "✅ Successfully pulled from $repo"
      return 0
    else
      echo "❌ Failed to pull from $repo"
      echo "Failing back to next repository in the list..."
    fi
  done

  echo "🚨 All attempts failed. Please check your network or remote URLs."
  exit 1
}
# end of module functions

# get_repo

if ! yadm pull; then
  echo "yadm pull found existing files"
  check_command tar
  echo "Backing up existing dotfiles..."
  cd $HOME
  yadm_files=$tmpdir/yadm_files.txt
  yadm ls-files | grep -v "readme.md" >$yadm_files
  tar -czf backup-dotfiles-$(date +%F-%H%M%S).tar.gz -T $yadm_files -C $HOME
  echo "Removing existing dotfiles..."
fi

if ! yadm submodule update --init --recursive; then
  echo "Failed to update submodules. Please check your network or submodule URLs."
  exit 1
fi
